### PR TITLE
🇧🇷 - Add Portuguese translations

### PR DESCRIPTION
**Pull request by Solynhoo**
**Hello**! First of all I love this project and I thought it would be nice to translate it to my native language and soo allowing more people get to know this project, I think cobalt is a game changer and such a nice project

There will be probably be some errors on the translation, soo if anyone wanna suggest some changes, hit me up! :D

### CODE REVIEW

**Comment by Solynhoo** [comment]
I saw a comment by _wukko_ saying to add translations to **Crowdin** but I think it got taken down becase I can't acess it :(
crowdin

**Comment by axui2** [comment]
> I saw a comment by _wukko_ saying to add translations to **Crowdin** but I think it got taken down becase I can't acess it :( crowdin

same here. crowdin is actually easier to use and translate there. much MUCH easier.

**Comment by synzr** [comment]
wukko closed the crowdin because community translations was always outdated and non-full from english/russian versions.

**Comment by Solynhoo** [comment]
> wukko closed the crowdin because community translations were always outdated and incomplete than english/russian versions.

I think he should re-open it
Cobalt is getting popular over the days and I think having open translations again would be good

**Comment by axui2** [comment]
> wukko closed the crowdin because community translations were always outdated and incomplete than english/russian versions.

can't people edit them though?

**Comment by Solynhoo** [comment]
**Kinda bored (and busy) to update it, sorry!**
Gonna close this, if anyone wants to use any of these translations as a starter and re-create a portuguese translation for cobalt, it would be highly appreciated!

**Have a good one, everybody <3**

**Pull request closed without merging**
