### PR TITLE
feat: add filename attributes to twitch clips

### PR DESCRIPTION
**Pull request by Snazzah**
Would be good for twitch clips to use their titles, so this should work fine.

I could also do tiktok but I might have to remove hashtags for that.

### CODE REVIEW

**Review by dumbmoron — APPROVED** [review]
lgtm

**Comment by dumbmoron** [comment]
actually `fileMetadata` should be `clipMetadata` but otherwise yah

**Review by wukko — APPROVED** [review]
👍

**Review by wukko — APPROVED** [review]
cleaning may be unnecessary but yeah

**Pull request merged**
